### ISSUE TITLE
Documenter l'option --interface

### ISSUE THREAD

**Issue by jmerdy** [punchplatform/punchbox#16]
Dans le fichier punch/readme.md il serait interressant de connaitre l'existance de cette option qui permet de définir l'interface d'écoute des machines sur lesquelles ont déploie

```
punchbox --config configurations/complete_punch_16G.json \
        --punch-conf <path_to_your_punchplatform_config_folder> \
        --deployer <path_to_your_punchplatform_deployer_zip> \
        --interface <host_network_interface>
```

Cordialement

**Comment by KaioKei** [comment]
New details about the `punchbox` command inside the punch guide section, including the `--interface` option
