### ISSUE TITLE
Valgrant obligatoire pour installer la punchbox

### ISSUE THREAD

**Issue by jmerdy** [punchplatform/punchbox#30]
Bonjour,

Lorsque l'on essaye d'installer la punchbox la vérification de valgrant bloque lorsqu'il n'est pas présent. Dans le cadre d'un déploiement sur des serveurs physique valgrant n'est pas nécessaire et ne bloqué pas lors des précédente version.

Peut-on pemettre l'installation de la punchbox sans valgrant ?

J'ai pour le moment commenté la partie valgrant du makefile parent.

Jérémy

**Comment by dimitripunch** [comment]
Jéremy je ne crois plus que tu utilises la punchbox. Je me permets de fermer ceci. On lui donne une seconde jeunesse.
