### ISSUE TITLE
Makefile out of control

### ISSUE THREAD

**Issue by dimitripunch** [punchplatform/punchbox#33]
The Makefile seems to be out of control ! First it is apparently full of linux specific punch specif things. This violates its original purpose of being portable and free (as far as possible) from punch specific features. 

Next : the doc says :

make vagrant-dependencies
make: *** No rule to make target `vagrant-dependencies'.  Stop.

**Comment by dimitripunch** [comment]
Also : 

~/Punch/punchbox $ make install
-e \x1b[34m  ************ CREATE PYTHON 3 .venv VIRTUALENV ************\x1b[0m
-e \x1b[34m  Python 3 virtualenv installed:\x1b[0m /Users/dimi/Punch/punchbox/.venv
-e \x1b[32m  ************ ADDING VAGRANT DEPENDENCIES ************\x1b[0m

the colors are not portable.

**Comment by dimiPunch** [comment]
Ok all good now. this Jonathan for the work.
